---
# tasks file for redis
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

#- name: Define redis_package.
#  set_fact:
#    redis_package: "{{ __redis_package }}"
#  when: redis_package is not defined

# Setup/install tasks.
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Copy execution file
  copy:
    src: "{{redis_src_dir}}/{{item}}"
    dest: "{{redis_exe_dir}}"
    owner: "{{redis_user}}"
    group: "{{redis_group}}"
    mode: 0755
    remote_src: yes
  with_items:
    - redis-server
    - redis-cli
  when: ansible_os_family == 'Debian'

- name: Ensure Redis is configured.
  template:
    src: redis.conf.j2
    dest: "{{redis_conf_dir}}/redis.conf"
    owner: "{{redis_user}}"
    group: "{{redis_group}}"
    mode: 0755
  notify: restart redis

- name: Config Redis run as service by systemd
  template:
    src: redis.service.j2
    dest: "{{redis_service_dir}}/redis.service"
    owner: "{{redis_user}}"
    group: "{{redis_group}}"
    mode: 0755
  when: ansible_os_family == 'Debian'

- name: Make sure Redis service is running
  systemd:
    daemon_reload: yes
    state: restarted
    name: "{{redis_daemon}}"
    enabled: yes
