---
# defaults file for jenkins
# Define jenkins version to download and install, empty to default latest version
jenkins_version: "2.201"
jenkins_package_state: present

jenkins_connection_delay: 5
jenkins_connection_retries: 60
# Define jenkins home
jenkins_home: /var/lib/jenkins
# Define jenkins server
jenkins_hostname: localhost
# Define jenkins port
jenkins_http_port: 8080
jenkins_jar_location: /opt/jenkins-cli.jar
jenkins_url_prefix: ""
jenkins_java_options: "-Djenkins.install.runSetupWizard=false"

jenkins_plugins: []
jenkins_plugins_state: present
jenkins_plugin_updates_expiration: 86400
jenkins_plugin_timeout: 30
jenkins_plugins_install_dependencies: true
# Define jenkins admin user
jenkins_admin_username: admin
jenkins_admin_password: admin
jenkins_admin_password_file: ""

jenkins_process_user: jenkins
jenkins_process_group: "{{ jenkins_process_user }}"

jenkins_init_changes:
  - option: "JENKINS_ARGS"
    value: "--prefix={{ jenkins_url_prefix }}"
  - option: "{{ jenkins_java_options_env_var }}"
    value: "{{ jenkins_java_options }}"
