---
# defaults file for zabbix
zb_version: "4.0"
zb_docpath: /usr/share/doc
zb_download_path: /tmp
zb_url_rpm: https://repo.zabbix.com/zabbix/{{zb_version}}/rhel/7/x86_64/zabbix-release-{{zb_version}}-1.el7.noarch.rpm
zb_url_deb: https://repo.zabbix.com/zabbix/{{zb_version}}/ubuntu/pool/main/z/zabbix-release/zabbix-release_{{zb_version}}-2+{{ansible_distribution_release}}_all.deb
zb_repo:  zabbix-release_{{zb_version}}-2+{{ansible_distribution_release}}_all.deb
