- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: setup-RedHat-package.yml
  when: ansible_os_family == 'RedHat' and not install_from_source

- include_tasks: setup-RedHat-source.yml
  when: ansible_os_family == 'RedHat' and install_from_source
