---
- name: Setup gcc pcre-static pcre-devel
  yum: pkg="{{RedHat_packs}}" state=present

- name: Ensure group HAproxy exists
  group:
    name: "{{haproxy_group}}"
    state: present

- name: Add the user HAproxy
  user:
    name: "{{haproxy_user}}"
    group: "{{haproxy_group}}"
    create_home: no
    shell: /sbin/nologin
    comment: "HAproxy User"
    state: present

- name: Create HAproxy folder
  file: path="{{item}}" state=directory mode=0700 owner=root
  with_items:
    - "{{haproxy_dir}}"
    - /etc/haproxy
    - /run/haproxy
    - /var/lib/haproxy

- name: Extract source code
  unarchive:
    src: "{{haproxy_url}}"
    dest: "{{haproxy_dir}}"
    remote_src: yes
    extra_opts: [--strip-components=1]

- name: Check HAproxy already installed
  stat:
    path: /usr/local/sbin/haproxy
  register: haproxy

- name: Compile source code
  command: make TARGET=linux-glibc CPU=generic USE_LINUX_TPROXY=1 USE_GETADDRINFO=1 USE_ZLIB=1 USE_REGPARM=1 USE_OPENSSL=1 USE_PCRE=1 USE_THREAD=1
  args:
    chdir: "{{haproxy_dir}}"
  register: compile
  when: not haproxy.stat.exists

- name: Ensure HAproxy is installed.
  make: chdir="{{haproxy_dir}}" target=install

- name: Add HAproxy symlink to /usr/local/bin.
  file:
    src: /usr/local/sbin/haproxy
    dest: /usr/sbin/haproxy
    state: link
    mode: 0755

- name: Add HAproxy init script.
  become: true
  template:
    src: haproxy.service.j2
    dest: /etc/systemd/system/haproxy.service
    mode: 0755
  notify: reload systemd

- name: Add HAproxy symlink
  file:
    src: /etc/systemd/system/haproxy.service
    dest: /etc/systemd/system/multi-user.target.wants/haproxy.service
    state: link
    mode: 0755

- name: Copy HAproxy configuration in place.
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644
    validate: haproxy -f %s -c -q
  notify: restart haproxy

- name: Ensure HAproxy is started and enabled on boot.
  service: name=haproxy state=started enabled=yes
