---
# tasks file for mongodb
- name: Install github python lib
  pip:
    name: github3.py

- name: Get latest release of repository
  github_release:
    user: percona
    repo: mongodb_exporter
    action: latest_release
  register: release

- name: Print latest release of repository
  debug:
    var: release.tag

- name: Set Mongodb_exporter latest version to download
  set_fact:
    mongodb_exporter_latest_version: "{{release.tag | regex_replace('v','')}}"

- name: Check Mongodb_exporter directory
  stat: path="{{mongodb_exporter_dir}}"
  register: dir_mongodb_exporter

- name: Download and extract Mongodb_exporter packages
  unarchive:
    src: 'https://github.com/percona/mongodb_exporter/releases/download/{{release.tag}}/mongodb_exporter-{{mongodb_exporter_latest_version}}.linux-amd64.tar.gz'
    dest: "{{mongodb_exporter_download_dir}}"
    owner: mongodb
    group: mongodb
    remote_src: yes
  when: not dir_mongodb_exporter.stat.exists

- name: Copy execute Mongodb_exporter file
  copy:
    src: "{{mongodb_exporter_dir}}"
    dest: "{{mongodb_exporter_execute_dir}}"
    owner: mongodb
    group: mongodb
    remote_src: yes
    mode: 0755

- name: Create Mongodb_exporter service
  template:
    src: mongodb-exporter.service.j2
    dest: "{{mongodb_exporter_service_dir}}/mongodb-exporter.service"

- name: Make sure Mongodb_exporter service is running
  systemd:
    daemon_reload: yes
    state: restarted
    name: mongodb-exporter
    enabled: yes
