---
# tasks file for mongodb
- name: Create the file to initialize the replicaset
  template: src=repset_init.js.j2 dest=/home/repset_init.js mode=0755
  when: inventory_hostname in groups['mongo_master']

- name: Initialize the replication set on the primary
  shell: mongo -u "{{ mongodb_admin_user['name'] }}" -p "{{ mongodb_admin_user['password'] }}" --authenticationDatabase "{{ mongodb_admin_user['database'] }}" < /home/repset_init.js
  run_once: true
  retries: 3
  delay: 3
  register: result
  until: result.rc == 0
  when: inventory_hostname in groups['mongo_master']
