- name: Installing Pre-Reqs
  apt:
    name: ["apt-transport-https", "python-pip"]
    state: present
  become: true
  register: result
  until: result is successful

- name: Adding MongoDB Repo Key
  apt_key:
    keyserver: "{{ mongodb_apt_keyserver }}"
    id: "{{ mongodb_apt_key_id[mongodb_version] }}"
    state: present
  become: true
  register: result
  until: result is successful

- name: Adding MongoDB Apt Repo
  apt_repository:
    repo: "{{ mongodb_apt_repo_ubuntu }}"
    state: present
  become: true
  register: result
  until: result is successful
  when: ansible_distribution == "Ubuntu"

- name: Installing MongoDB
  apt:
    name: ["mongodb-org", "mongodb-org-server"]
    state: present
  become: true
  register: result
  until: result is successful

- name: Enabling and Starting MongoDB Service
  service:
    name: mongod
    state: started
    enabled: true
  become: true
