- hosts: all
  become: yes
  become_user: root
  gather_facts: no
##  Setup python( if none) before run roles
  pre_tasks:
    - name: Setup python on Ubuntu server
      raw: apt-get install -y python-minimal
      ignore_errors: yes
      no_log: yes
      register: python_Debian
    - name: Setup python on Centos server
      raw: yum install -y python
      when: python_Debian is failed

    - name: Gather Facts
      setup:
##  Example to define software version from input.
##  Note to "name" same as name variable of software you define in setup task.
##  Repeat "vars_prompt name" depend on software what you want to install.
##  If you had set variable in vars/xxx.yml, variable from input will not work.
##  Follow this link to see the order of variable priority https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#passing-variables-on-the-command-line
#  vars_prompt:
#    - name: "software version"
#      prompt: "What software version do you want to install?"
#      default: "x.x"
#      private: no ## Show variable when typing
  roles:
   - base
   - mongodb
#   - nginx
#   - apache2
#   - mysql
#   - php
#   - zabbix
#   - nodejs
#   - java
#   - tomcat
#   - jenkins
#   - composer
#   - wordpress
#   - haproxy
#   - redis
#   - zabbix-agent
#   - elasticsearch
#   - kibana
#   - logstash
#   - filebeat
#   - firewall
