---
# tasks file for wordpress
- include_vars: site.yml
  when: not multi_site
- include_vars: multi-sites.yml
  when: multi_site
- include_tasks: setup.yml
- include_tasks: create&importDB.yml
- include_tasks: build.yml
- include_tasks: vhost.yml
- include_tasks: plugins.yml
- include_tasks: backupDB.yml
