---
# tasks file for zabbix-agent
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# Setup/install tasks.
- include_tasks: "setup-{{ ansible_os_family }}.yml"
- include_tasks: psk.yml
  when: psk_encrypted
- include_tasks: config.yml
- include_tasks: zabbix-hosts.yml
