---
# tasks file for zabbix-agent
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Gather facts from remote server
  setup:
    filter: "{{item}}"
  with_items:
    - ansible_distribution_version
    - ansible_nodename
    - ansible_default_ipv4.address

# Setup/install tasks.
- include_tasks: "setup-{{ ansible_os_family }}.yml"
- include_tasks: config.yml
- include_tasks: zabbix-hosts.yml
