---
# tasks file for zabbix-agent
- name: Install the Zabbix repo.
  yum:
   name: "{{zabbix_rpm_url}}"
   state: present
  register: zb_repo

- name: install Zabbix-agent
  yum:
    name: "{{zabbix_agent}}"
    update_cache: yes
    state: latest

- name: Ensure zabbix-agent is started and enabled to start at boot.
  service: name=zabbix-agent state=started enabled=yes
