---
- name: Gather facts from remote server
  setup:
    filter: ansible_distribution_version

- name: Install deb packages
  apt:
    deb: https://repo.zabbix.com/zabbix/4.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_4.0-2+xenial_all.deb
  when: ansible_distribution_version == '16.04'

- name: Install deb packages
  apt:
    deb: https://repo.zabbix.com/zabbix/4.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_4.0-2+bionic_all.deb
  when: ansible_distribution_version == '18.04'

- name: install Zabbix-agent
  become: true
  apt:
    name: "{{packages}}"
    update_cache: yes
    state: latest
  vars:
    packages:
    - zabbix-agent
    - zabbix-sender
    - zabbix-java-gateway

- name: Ensure zabbix-agent is started and enabled to start at boot.
  service: name=zabbix-agent state=started enabled=yes
