---
- name: Install deb packages
  apt:
    deb: "{{zabbix_deb_url}}"

- name: install Zabbix-agent
  apt:
    name: "{{zabbix_agent}}"
    update_cache: yes
    state: present

- name: Ensure zabbix-agent is started and enabled to start at boot.
  service: name=zabbix-agent state=started enabled=yes
