---
# tasks file for zabbix-agent
- name: Install the Zabbix repo.
  yum:
   name: https://repo.zabbix.com/zabbix/4.0/rhel/7/x86_64/zabbix-release-4.0-1.el7.noarch.rpm
   state: present
  register: zb_repo

- name: install Zabbix-agent
  become: true
  yum:
    name: "{{packages}}"
    update_cache: yes
    state: latest
  vars:
    packages:
    - zabbix-agent
    - zabbix-sender
    - zabbix-java-gateway

- name: Ensure zabbix-agent is started and enabled to start at boot.
  service: name=zabbix-agent state=started enabled=yes
