---
# tasks file for rabbitmq
- name: Check hosts group before run config cluster playbook
  fail:
    msg: "Please define hostgroup 'rabbit-cluster' in ansible hosts file before run playbook"
  when:
    - "'rabbit-cluster' not in groups"
    - cluster|bool

- include_tasks: setup-erlang.yml

- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: config.yml
- include_tasks: cluster.yml
  when: cluster
- include_tasks: users.yml
  when: (cluster and inventory_hostname == groups["rabbit_cluster"][0]) or (not cluster)

- name: Ensure rabbitmq is started and enabled (if configured).
  service:
    name: "{{ rabbitmq_daemon }}"
    state: "{{ rabbitmq_state }}"
    enabled: "{{ rabbitmq_enabled }}"

- import_tasks: rabbitmq_exporter.yml
  when: (rabbitmq_exporter and cluster and inventory_hostname == groups["rabbit_cluster"][0]) or (rabbitmq_exporter and not cluster)
  tags: rabbitmq-exporter
