---
# tasks file for rabbitmq
- include: setup-erlang.yml

- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: config.yml
- include_tasks: cluster.yml
  when: cluster
- include_tasks: users.yml

- name: Ensure rabbitmq is started and enabled (if configured).
  service:
    name: "{{ rabbitmq_daemon }}"
    state: "{{ rabbitmq_state }}"
    enabled: "{{ rabbitmq_enabled }}"
