---
# tasks file for rabbitmq
- name: Check Rabbitmq_exporter directory
  stat: path="{{rabbitmq_exporter_dir}}"
  register: dir_rabbitmq_exporter

- name: Download and extract Rabbitmq_exporter packages
  unarchive:
    src: "{{rabbitmq_exporter_url}}"
    dest: "{{rabbitmq_exporter_download_dir}}"
    owner: rabbitmq
    group: rabbitmq
    remote_src: yes
  when: not dir_rabbitmq_exporter.stat.exists

- name: Copy execute Rabbitmq_exporter file
  copy:
    src: "{{rabbitmq_exporter_dir}}/{{item}}"
    dest: "{{rabbitmq_exporter_execute_dir}}"
    owner: rabbitmq
    group: rabbitmq
    remote_src: yes
    mode: 0755
  with_items:
    - rabbitmq_exporter

- name: Create Rabbitmq_exporter service
  template:
    src: rabbitmq-exporter.service.j2
    dest: "{{rabbitmq_exporter_service_dir}}/rabbitmq-exporter.service"

- name: Make sure Rabbitmq_exporter service is running
  systemd:
    daemon_reload: yes
    state: restarted
    name: rabbitmq-exporter
    enabled: yes
