---
# tasks file for rabbitmq
- name: Check erlang file
  stat: path="{{erlang_download_dir}}/{{erlang_deb_file}}"
  register: file_erlang_deb
  when: ansible_os_family == 'Debian'

- name: Download erlang deb package
  get_url:
    url: "{{erlang_deb_url}}"
    dest: "{{erlang_download_dir}}"
  when: ansible_os_family == 'Debian' and not file_erlang_deb.stat.exists

- name: Install erlang deb packages
  apt:
    deb: "{{erlang_download_dir}}/{{erlang_deb_file}}"
    force: yes
  when: ansible_os_family == 'Debian'

- name: Install erlang repos
  yum:
    name: "{{erlang_rpm_url}}"
    state: present
  when: ansible_os_family == 'RedHat'

- name: Install erlang packages
  yum:
    name: "{{erlang_package}}"
    state: present
    update_cache: yes
  when: ansible_os_family == 'RedHat'
