---
# tasks file for firewall
- ufw:
    rule: allow
    port: 22
    proto: tcp

- ufw:
    rule: allow
    port: 80
    proto: tcp

- ufw:
    rule: allow
    port: 443
    proto: tcp

- ufw:
    rule: allow
    port: 10050
    proto: tcp

- ufw:
    state: enabled
  notify: reload firewall
