---
# defaults file for tomcat
tomcat_major_version: "8"
tomcat_version: "8.5.42"
tomcat_username: tomcat
tomcat_group: tomcat
tomcat_base_dir: /opt
tomcat_catalina_home: "{{ tomcat_base_dir }}/tomcat"
tomcat_url: https://archive.apache.org/dist/tomcat/tomcat-{{tomcat_major_version}}/v{{tomcat_version}}/bin/apache-tomcat-{{tomcat_version}}.tar.gz
tomcat_service_dir: /etc/systemd/system
tomcat_xms: 512M
tomcat_xmx: 1024M
