---
# tasks file for certbot
- name: Install Certbot.
  package: "name={{ certbot_package }} state=present"
  retries: 3
  delay: 3
  register: result
  until: result.rc == 0

- name: Set Certbot script variable.
  set_fact:
    certbot_script: "{{ certbot_package }}"
