---
# tasks file for cerebro
- name: Check Cerebro file
  stat: path="{{cerebro_dir}}"
  register: file_cerebro

- name: Extract Cerebro
  unarchive:
    src: "{{cerebro_url}}"
    dest: /home
    owner: root
    group: root
    remote_src: yes
  when: not file_cerebro.stat.exists

- name: Add service script
  template:
    src: cerebro.service
    dest: /etc/systemd/system/cerebro.service
    owner: root
    group: root
    mode: 0755

- name: Reload daemon
  systemd:
    daemon_reload: yes

- name: Start and enable cerebro on boot
  systemd:
    name: cerebro
    state: restarted
    enabled: yes
