---
# defaults file for redis
# Define redis version to download
redis_version: "5.0.4"
# Define redis url download
redis_url: http://download.redis.io/releases/redis-{{redis_version}}.tar.gz
redis_download_dir: /tmp
# Define redis directory
redis_dir: "{{redis_download_dir}}/redis-{{redis_version}}"
redis_src_dir: "{{redis_dir}}/src"
redis_db_dir: /var/lib/redis
redis_exe_dir: /usr/local/bin
redis_log_dir: /var/log/redis
redis_service_dir: /etc/systemd/system
# Enable redis remi repos for Centos7
redis_enablerepo: "remi"
redis_user: redis
redis_group: redis
# Redis config options
redis_port: 6379
redis_bind_interface: 0.0.0.0
redis_unixsocket: ''
redis_timeout: 300
redis_loglevel: "notice"
redis_logfile: /var/log/redis/redis-server.log
redis_databases: 16
# Set to an empty set to disable persistence (saving the DB to disk).
redis_save:
  - 900 1
  - 300 10
  - 60 10000
redis_rdbcompression: "yes"
redis_dbfilename: dump.rdb
redis_maxmemory: 0
redis_maxmemory_policy: "noeviction"
redis_maxmemory_samples: 5
redis_appendonly: "no"
redis_appendfsync: "everysec"
# Add extra include files for local configuration/overrides.
redis_includes: []
# Require authentication to Redis with a password.
redis_requirepass: ""
# Disable certain Redis commands for security reasons.
redis_disabled_commands: []
