---
# tasks file for tomcat
- name: Check java installed
  shell: java -version 2>&1 | grep version | awk '{print $3}' | sed 's/"//g'
  register: java_result
  changed_when: False

- fail:
    msg: "Java is not installed on this machines"
  when: "java_result.stdout == ''"
  
- name: Create Tomcat Group
  group:
    name: "{{ tomcat_group }}"
    state: present

- name: Create Tomcat user
  user:
    name: "{{ tomcat_username }}"
    group: "{{ tomcat_group }}"
    shell: /sbin/nologin
    createhome: no

- name: Create tomcat directory
  file:
    path: "{{tomcat_catalina_home}}"
    state: directory
    owner: "{{tomcat_username}}"
    group: "{{tomcat_group}}"

- name: Download and extract Tomcat package
  unarchive:
    src: "{{tomcat_url}}"
    dest: "{{tomcat_catalina_home}}"
    owner: "{{tomcat_username}}"
    group: "{{tomcat_group}}"
    remote_src: yes
    extra_opts: [--strip-components=1]

- name: Create Tomcat service
  template:
    src: tomcat.service.j2
    dest: "{{tomcat_service_dir}}/tomcat.service"
    owner: "{{tomcat_username}}"
    group: "{{tomcat_group}}"

- name: Make sure Tomcat service is running
  systemd:
    daemon_reload: yes
    state: restarted
    name: tomcat
    enabled: yes
