---
# tasks file for elasticsearch
- name: Configure Elasticsearch.
  template:
    src: elasticsearch-cluster.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
    mode: 0660
  notify: restart elasticsearch
  when: cluster

- name: Configure Elasticsearch.
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
    mode: 0660
  notify: restart elasticsearch
  when: not cluster

- name: Force a restart if configuration has changed.
  meta: flush_handlers

- name: Ensure Elasticsearch start on boot
  service:
    name: elasticsearch
    state: started
    enabled: yes

- name: Make sure Elasticsearch is running before proceeding.
  wait_for:
    host: "{{ elasticsearch_network_host }}"
    port: "{{ elasticsearch_http_port }}"
    delay: 3
    timeout: 300
