---
# tasks file for elasticsearch
- name: Create backup directory for Elasticsearch.
  file:
    path: "{{es_backup_dir}}"
    state: directory
    mode: 0700
    owner: elasticsearch
    group: elasticsearch

- name: Configure Elasticsearch cluster roles "Master".
  template:
    src: elasticsearch-cluster-master.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
    mode: 0660
  notify: restart elasticsearch
  when: "'master' in inventory_hostname and cluster_set_roles"

- name: Configure Elasticsearch cluster roles "Node".
  template:
    src: elasticsearch-cluster-node.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
    mode: 0660
  notify: restart elasticsearch
  when: "'node' in inventory_hostname and cluster_set_roles"

- name: Configure Elasticsearch cluster all roles.
  template:
    src: elasticsearch-cluster.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
    mode: 0660
  notify: restart elasticsearch
  when: cluster

- name: Configure Elasticsearch single.
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
    mode: 0660
  notify: restart elasticsearch
  when: not cluster

- name: Setup plugin
  elasticsearch_plugin:
    name: "{{plugins}}"
    state: present

- name: Force a restart if configuration has changed.
  meta: flush_handlers

- name: Ensure Elasticsearch start on boot
  service:
    name: elasticsearch
    state: started
    enabled: yes

- name: Make sure Elasticsearch is running before proceeding.
  wait_for:
    host: "{{ elasticsearch_network_host }}"
    port: "{{ elasticsearch_http_port }}"
    delay: 3
    timeout: 300
