---
# tasks file for elasticsearch
- name: Install github python lib
  pip:
    name: github3.py

- name: Get latest release of repository
  github_release:
    user: justwatchcom
    repo: elasticsearch_exporter
    action: latest_release
  register: release

- name: Print latest release of repository
  debug:
    var: release.tag

- name: Set Elasticsearch_exporter latest version to download
  set_fact:
    es_exporter_latest_version: "{{release.tag | regex_replace('v','')}}"

- name: Check Elasticsearch_exporter directory
  stat: path="{{es_exporter_dir}}"
  register: dir_es_exporter

- name: Download and extract Elasticsearch_exporter packages
  unarchive:
    src: 'https://github.com/justwatchcom/elasticsearch_exporter/releases/download/{{release.tag}}/elasticsearch_exporter-{{es_exporter_latest_version}}.linux-amd64.tar.gz'
    dest: "{{es_exporter_download_dir}}"
    owner: elasticsearch
    group: elasticsearch
    remote_src: yes
  when: not dir_es_exporter.stat.exists

- name: Copy execute Elasticsearch_exporter file
  copy:
    src: "{{es_exporter_dir}}/{{item}}"
    dest: "{{es_exporter_execute_dir}}"
    owner: elasticsearch
    group: elasticsearch
    remote_src: yes
    mode: 0755
  with_items:
    - elasticsearch_exporter

- name: Create Elasticsearch_exporter service
  template:
    src: elasticsearch-exporter.service.j2
    dest: "{{es_exporter_service_dir}}/elasticsearch-exporter.service"

- name: Make sure Elasticsearch_exporter service is running
  systemd:
    daemon_reload: yes
    state: restarted
    name: elasticsearch-exporter
    enabled: yes
