---
# tasks file for elasticsearch
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Elasticsearch.
  package:
    name: elasticsearch
    state: latest

- include_tasks: config.yml

- import_tasks: elasticsearch_exporter.yml
  when: elasticsearch_exporter and inventory_hostname in groups['es_master']
  tags: es-exporter
