---
# tasks file for base
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# Setup/install tasks.
- include_tasks: "setup-{{ ansible_os_family }}.yml"

- import_tasks: hostname.yml
  tags: hostname

- import_tasks: timezone.yml
  tags: timezone

- import_tasks: optimize.yml
  tags: optimize

- name: Define pip verson to install
  set_fact:
    python_pip_version: "{% if 'python3' in ansible_python_interpreter|default('') %}python3-pip,python3-setuptools{% else %}python-pip,python-setuptools{% endif %}"

- debug:
    var: python_pip_version

- name: Install pip
  package:
    name: "{{ python_pip_version }}"
    state: present

- name: Upgrade pip version
  pip:
    name: pip
    extra_args: --upgrade

- name: Install AWS CLI
  pip:
    name: awscli
    extra_args: "{{ item }}"
  with_items: "{{ extra_args }}"
  tags: awscli
