---
# tasks file for base
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# Setup/install tasks.
- include_tasks: "setup-{{ ansible_os_family }}.yml"

- import_tasks: hostname.yml
  tags: hostname

- import_tasks: timezone.yml
  tags: timezone

- import_tasks: optimize.yml
  tags: optimize

- name: Upgrade pip version
  pip:
    name: pip
    extra_args: --upgrade
    
- name: Install AWS CLI
  pip:
    name: awscli
    extra_args: "{{ item }}"
  with_items: "{{ extra_args }}"
  tags: awscli
