---
# tasks file for base
- name: new variable with current date time
  set_fact: temp="{{lookup('pipe','date \"+%Y-%m-%d %H:%M\"')}}"

- name: print variable
  debug: msg="Current date and time is {{temp}}"

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- include_tasks: hostname.yml
# Setup/install tasks.
- include_tasks: "setup-{{ ansible_os_family }}.yml"

- name: Increase the limited max number of connections
  blockinfile:
    path: /etc/sysctl.conf
    block: |
      net.ipv4.netfilter.ip_conntrack_max = 1048576
      net.nf_conntrack_max = 1048576
      net.core.somaxconn = 65535
      vm.overcommit_memory = 1
    backup: yes

- name: Increase the limited max number of open files
  blockinfile:
    path: /etc/security/limits.conf
    block: |
      * soft nofile 1000000
      * hard nofile 1000000
      root soft nofile 1000000
      root hard nofile 1000000
    backup: yes

- name: Limit resource per user
  lineinfile:
    path: /etc/pam.d/common-session
    line: session required  pam_limits.so
