---
# tasks file for base
- name: new variable with current date time
  set_fact: temp="{{lookup('pipe','date \"+%Y-%m-%d %H:%M\"')}}"

- name: print variable
  debug: msg="Current date and time is {{temp}}"

- name: insert/update "LC_ALL" configuration block in /etc/default/locale
  blockinfile:
    path: /etc/default/locale
    block: |
      LANGUAGE="en_US:"
      LANG="en_US.UTF-8"
      LC_ALL="en_US.UTF-8"
      LC_CTYPE="en_US.UTF-8"

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- include_tasks: hostname.yml
# Setup/install tasks.
- include_tasks: "setup-{{ ansible_os_family }}.yml"
