- name: Set selinux
  selinux:
    policy: targeted
    state: permissive
  notify: stop firewalld

- name: Install epel-release
  yum:
    name: epel-release
    state: latest

- name: Install Remi repos
  yum:
    name: http://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state: latest

- name: Install Server Basics
  yum: name={{ packages }} state=latest update_cache=true
