- name: Install Server Basics
  apt: name={{ packages }} state=present update_cache=yes

- name: insert/update "LC_ALL" configuration block in /etc/default/locale
  blockinfile:
    path: /etc/default/locale
    block: |
      LANGUAGE="en_US:"
      LC_ALL="en_US.UTF-8"
      LC_CTYPE="en_US.UTF-8"
