- name: Install Server Basics
  apt: name={{ packages }} state=present update_cache=yes

- name: Add Python3 Repository
  apt_repository:
    repo: ppa:jonathonf/python-3.6

- name: Setup Python3
  apt:
    name: python3.6
    state: present

- name: insert/update locale configuration block
  lineinfile:
    path: ~/.bashrc
    line: alias python='/usr/bin/python3.6'

- name: Export locale var
  shell: source ~/.bashrc
  args:
    executable: /bin/bash

- name: Export LC_ALL=C
  shell: export LC_ALL=C
