- name: Install Server Basics
  apt: name={{ packages }} state=present update_cache=yes

- name: insert/update locale configuration block
  blockinfile:
    path: ~/.bashrc
    block: |
      LANGUAGE="en_US:"
      LC_ALL="en_US.UTF-8"
      LC_CTYPE="en_US.UTF-8"

- name: Export locale var
  shell: source ~/.bashrc
  args:
    executable: /bin/bash
