- name: Install Server Basics
  apt: name={{ packages }} state=present update_cache=yes
  register: apt_res
  retries: 3
  until: apt_res is success

- name: insert/update locale configuration block
  blockinfile:
    path: ~/.bashrc
    block: |
      LANG=en_US.UTF-8
      LANGUAGE=en_US
      LC_CTYPE="en_US.UTF-8"
      LC_NUMERIC="en_US.UTF-8"
      LC_TIME="en_US.UTF-8"
      LC_COLLATE="en_US.UTF-8"
      LC_MONETARY="en_US.UTF-8"
      LC_MESSAGES="en_US.UTF-8"
      LC_PAPER="en_US.UTF-8"
      LC_NAME="en_US.UTF-8"
      LC_ADDRESS="en_US.UTF-8"
      LC_TELEPHONE="en_US.UTF-8"
      LC_MEASUREMENT="en_US.UTF-8"
      LC_IDENTIFICATION="en_US.UTF-8"
      LC_ALL=C
      alias python='/usr/bin/python2.7'

- name: Export locale var
  shell: source ~/.bashrc
  args:
    executable: /bin/bash
