- name: Install Server Basics
  apt: pkg={{ packages }} state=present update_cache=yes

- name: Increase the limited max number of connections
  blockinfile:
    path: /etc/sysctl.conf
    block: |
      net.ipv4.netfilter.ip_conntrack_max = 1048576
      net.nf_conntrack_max = 1048576
      net.core.somaxconn = 1048576
    backup: yes
