---
# defaults file for grafana-prometheus
# Define user,group
prometheus_user:   prometheus
prometheus_group:  prometheus
prometheus_download_dir: /tmp
# Define package name
prometheus_packages: prometheus-{{prometheus_latest_version}}.linux-amd64.tar.gz
# Define package name after extract
prometheus_dir: "{{prometheus_download_dir}}/prometheus-{{prometheus_latest_version}}.linux-amd64"
# Define url to download
prometheus_execute_dir: /usr/local/bin
# Define prometheus config directory
prometheus_config_dir: /etc/prometheus
prometheus_service_dir: /etc/systemd/system
prometheus_db_dir: /var/lib/prometheus
prometheus_log_dir: /var/log/prometheus
prometheus_pid_dir: /var/run/prometheus

# Define grafana version
grafana_version: 6.1.6
# Define url packages
grafana_url_deb: https://dl.grafana.com/oss/release/grafana_{{grafana_version}}_amd64.deb
grafana_url_rpm: https://dl.grafana.com/oss/release/grafana-{{grafana_version}}-1.x86_64.rpm

# Define alertmanager version
alertmanager_user: alertmanager
alertmanager_group: alertmanager
alertmanager_download_dir: /tmp
alertmanager_dir: "{{alertmanager_download_dir}}/alertmanager-{{alertmanager_latest_version}}.linux-amd64"
alertmanager_execute_dir: /usr/local/bin
alertmanager_service_dir: /etc/systemd/system/alertmanager.service
alertmanager_config_dir: /etc/alertmanager
alertmanager_data_dir: /data/alertmanager
# Define webhook slack url
slack_api_url: ''
# Define Alert rules
alertmanager_route: []
#  group_by: ['instance', 'severity']
#  group_wait: 30s
#  group_interval: 5m
#  repeat_interval: 3h
#  receiver: 'alert-team'
#  routes:
#  - match:
#      alertname: InstanceDown,LoadAverage1m,MemoryFree10%,DiskSpace10%Free

# Define slack channel name
alertmanager_receivers: []
#  - name: 'alert-team'
#    slack_configs:
#    - channel: "#test-grafana"

# Add this line below "channel" line.
## title: "{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
## text: "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"
