---
# tasks file for php
- name: Install software common
  apt: name=software-properties-common

- name: Add php repository
  apt_repository:
    repo: ppa:ondrej/php

- name: Ensure PHP packages are installed.
  apt:
    name: "{{ php_packages }}"
    state: present
    update_cache: true
  register: php_package_install
  notify: restart php-fpm

- name: Enable mod php-cgi
  shell: a2enmod actions fastcgi alias proxy_fcgi

- name: Enabled php-fpm on boot.
  service: "name={{php_fpm_daemon}} state=started enabled=yes"
