---
# tasks file for zabbix
- name: Find zabbix databases files
  find:
    paths: "{{zb_docpath}}"
    file_type: directory
    patterns: 'zabbix-server-mysql-*'
  register: zbdb
  when: ansible_os_family == 'RedHat'

- name: Set zabbix databases path in Centos
  set_fact:
    zb_dbpath: "{{item.path}}"
  with_items: "{{ zbdb['files'] }}"
  when: ansible_os_family == 'RedHat'

- name: Create databases
  mysql_db:
    login_user: "{{mysql_root_username}}"
    login_password: "{{mysql_root_password}}"
    login_host: "{{mysqlhost}}"
    name: "{{item}}"
    state: present
  with_items:
    - "{{ DB1 }}"
  register: dbcreate

- name: Create zabbix user
  mysql_user:
    login_user: "{{mysql_root_username}}"
    login_password: "{{mysql_root_password}}"
    login_host: "{{mysqlhost}}"
    name: "{{DBUser}}"
    password: "{{DBPassword}}"
    host: "{{DBHost}}"
    priv: 'zabbixdb.*:ALL'
    state: present

- name: Import DB UserStore & Registry
  mysql_db:
    name: "{{item}}"
    state: import
    target: "{{zb_dbpath}}/create.sql.gz"
    login_user: "{{mysql_root_username}}"
    login_password: "{{mysql_root_password}}"
    login_host: "{{mysqlhost}}"
  with_items:
    - "{{ DB1 }}"
  when: dbcreate is changed and ansible_os_family == 'Debian'

- name: Import DB UserStore & Registry
  mysql_db:
    name: "{{item}}"
    state: import
    target: "{{zb_dbpath}}/create.sql.gz"
    login_user: "{{mysql_root_username}}"
    login_password: "{{mysql_root_password}}"
    login_host: "{{mysqlhost}}"
  with_items:
    - "{{ DB1 }}"
  when: dbcreate is changed and ansible_os_family == 'RedHat'
