---
# tasks file for zabbix
- name: Download Zabbix repo.
  get_url:
   url: "{{ zb_url_deb[ansible_distribution_release] }}"
   dest: /tmp
   timeout: 60
  register: zb_repo_deb

- name: Install Zabbix repos.
  apt:
    deb: "/tmp/{{ zb_repo[ansible_distribution_release] }}"
    state: present
  when: zb_repo_deb is changed

- name: Install Zabbix packages.
  apt:
    name: "{{ zb_pkg }}"
    state: present
    update_cache: true

- name: Setup Zabbix Apache Config
  template:
    src: "./zabbix.conf.j2"
    dest: "/etc/apache2/conf-enabled/zabbix.conf"
    mode: 0755
  notify: restart apache
