---
# tasks file for zabbix
- name: Check Apache installed
  shell: apachectl -v 2>&1 | grep version | awk '{print $3}' | sed 's/"//g'
  register: apache_result
  changed_when: False

- fail:
    msg: "Apache is not installed on this machines"
  when: "apache_result.stdout == ''"

- name: Check MySQL installed
  shell: mysql --version 2>&1 | grep version | awk '{print $3}' | sed 's/"//g'
  register: mysql_result
  changed_when: False

- fail:
    msg: "MySQL is not installed on this machines"
  when: "mysql_result.stdout == ''"

- name: Check PHP installed
  shell: php -v 2>&1 | grep version | awk '{print $3}' | sed 's/"//g'
  register: php_result
  changed_when: False

- fail:
    msg: "PHP is not installed on this machines"
  when: "php_result.stdout == ''"

- name: Download Zabbix repo.
  get_url:
   url: "{{ zb_url_deb}}"
   dest: "{{zb_download_path}}"
   timeout: 60
  register: zb_repo_deb

- name: Install Zabbix repos.
  apt:
    deb: "{{zb_download_path}}/{{ zb_repo }}"
    state: present
  when: zb_repo_deb is changed

- name: Install Zabbix packages.
  apt:
    name: "{{ zb_pkg }}"
    state: present
    update_cache: true

- name: Setup Zabbix Apache Config
  template:
    src: "./zabbix.conf.j2"
    dest: "/etc/apache2/conf-enabled/zabbix.conf"
    mode: 0755
  notify: restart apache
