---
# tasks file for zabbix
- name: Check Apache installed
  shell: httpd -v 2>&1 | grep version | awk '{print $3}' | sed 's/"//g'
  register: httpd_result
  changed_when: False

- fail:
    msg: "Apache is not installed on this machines"
  when: "httpd_result.stdout == ''"

- name: Check MySQL installed
  shell: mysql --version 2>&1 | grep version | awk '{print $3}' | sed 's/"//g'
  register: mysql_result
  changed_when: False

- fail:
    msg: "MySQL is not installed on this machines"
  when: "mysql_result.stdout == ''"

- name: Check PHP installed
  shell: php -v 2>&1 | grep version | awk '{print $3}' | sed 's/"//g'
  register: php_result
  changed_when: False

- fail:
    msg: "PHP is not installed on this machines"
  when: "php_result.stdout == ''"

- name: Install the Zabbix repo.
  yum:
   name: "{{zb_url_rpm}}"
   state: present
  register: zb_repo_rpm

- name: Ensure Zabbix packages are installed.
  yum:
    name: "{{zb_pkg}}"
    state: present
  when: zb_repo_rpm is changed

- name: Setup Zabbix Apache Config
  template:
    src: "./zabbix.conf.j2"
    dest: "/etc/httpd/conf.d/zabbix.conf"
    mode: 0755
  notify: restart apache
