---
# tasks file for grafana-alert_manager
- name: create Alertmanager group
  group: name={{ alert_manager_group }} state=present

- name: create Alertmanager user
  user:
    name: "{{ alert_manager_user }}"
    group: "{{ alert_manager_group }}"
    create_home: no
    shell: /sbin/nologin
    comment: "Alertmanager User"
    state: present

- name: Creates data directory
  file:
    path: "{{item}}"
    state: directory
    owner: "{{alert_manager_user}}"
    group: "{{alert_manager_group}}"
    mode: 0755
  with_items:
    - "{{alert_manager_config_dir}}"
    - "{{alert_manager_data_dir}}"

- name: Check Alertmanager directory
  stat: path="{{alert_manager_dir}}"
  register: dir_alert_manager

- name: Download and extract Alertmanager packages
  unarchive:
    src: "{{alert_manager_url}}"
    dest: "{{alert_manager_download_dir}}"
    owner: "{{alert_manager_user}}"
    group: "{{alert_manager_group}}"
    remote_src: yes
  when: not dir_alert_manager.stat.exists

- name: Copy execute Alertmanager file
  copy:
    src: "{{alert_manager_dir}}/{{item}}"
    dest: "{{alert_manager_execute_dir}}"
    owner: "{{alert_manager_user}}"
    group: "{{alert_manager_group}}"
    remote_src: yes
    mode: 0755
  with_items:
    - alertmanager

- name: Copy Alertmanager config
  template:
    src: alertmanager.yml.j2
    dest: "{{alert_manager_config_dir}}/alertmanager.yml"
    owner: "{{alert_manager_user}}"
    group: "{{alert_manager_group}}"

- name: Copy Alertmanager rules
  copy:
    src: files/rules.yml
    dest: "{{prometheus_config_dir}}/rules.yml"
    owner: "{{alert_manager_user}}"
    group: "{{alert_manager_group}}"

- name: Create Alertmanager service
  template:
    src: alertmanager.service.j2
    dest: "{{alert_manager_service_dir}}/alertmanager.service"

- name: Make sure Alertmanager service is running
  systemd:
    daemon_reload: yes
    state: restarted
    name: alertmanager
    enabled: yes
