---
# tasks file for grafana-prometheus
- name: Install github python lib
  pip:
    name: github3.py

- import_tasks: prometheus.yml
  tags: prometheus

- import_tasks: grafana.yml
  tags: grafana

- import_tasks: alertmanager.yml
  tags: alertmanager
